METAFILE: configs/metadata.csv
# REF = /home/data/yzpeng/3-Data/Ref/human/Homo_sapiens.GRCh38.dna.primary_assembly.fa
GTF: /home/data/yzpeng/3-Data/Ref/mouse/Mus_musculus.GRCm39.111.gtf.gz
HISAT2_INDEX: /home/data/yzpeng/3-Data/Ref/mouse/hisat2/Mus_musculus.GRCm39.dna.primary_assembly
THREADS: 16
