METAFILE: configs/metadata.csv
# REF = /home/data/yzpeng/3-Data/Ref/human/Homo_sapiens.GRCh38.dna.primary_assembly.fa
GTF: /home/data/yzpeng/3-Data/Ref/human/Homo_sapiens.GRCh38.111.gtf
# HISAT2_REF = /home/data/yzpeng/3-Data/Ref/human/hisat_test/test_10M
THREADS: 16
